dist: trusty
sudo: required
env:
  global:
    - export DISPLAY=:99.0
    - QT_ROOT="${TRAVIS_BUILD_DIR}/vendor/qt5"  
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
before_install:
# stuff needed for qt5 which is for GUI  
  - sudo apt-get -qq update
  - sudo apt-get install -qq qt5-dev-tools
  # test/start GUI
  - sh -e /etc/init.d/xvfb start
    # print configuration 
  - echo "Configuration info:"
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
before_script:
  # Run your build commands next
  - mkdir build
  - cd build/
  - cmake ../ -DEEMA_EXAMPLES=ON -DEXAMPLE1=ON -DEEMA_GUI=ON -DCMAKE_VERBOSE_MAKEFILE=ON
script:
  - make
  # test example 1 
  - cd examples/example-1;  
  - ./eema_example-1 ./ input.inp
  # test gui compile
  - ./gui/eema_gui
